--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--

local v0=game:GetService("Players");local v1=game:GetService("UserInputService");local v2=v0.LocalPlayer;local v3=Instance.new("ScreenGui");v3.ResetOnSpawn=false;v3.Parent=v2:WaitForChild("PlayerGui");local v6=Instance.new("Frame");v6.Size=UDim2.new(0.3,0,0.4,0);v6.Position=UDim2.new(0.35,0,0.3,0);v6.BackgroundColor3=Color3.fromRGB(5,0,0);v6.Parent=v3;local v11=Instance.new("TextLabel");v11.Size=UDim2.new(1,0,0.2,0);v11.BackgroundColor3=Color3.fromRGB(255,10,0);v11.Text="gimme the key pls";v11.TextColor3=Color3.new(1,1,1);v11.Font=Enum.Font.GothamBlack;v11.TextSize=24;v11.Parent=v6;local v20=Instance.new("TextBox");v20.Size=UDim2.new(0.8,0,0.18,0);v20.Position=UDim2.new(0.1,0,0.32,0);v20.PlaceholderText="Type it";v20.BackgroundColor3=Color3.fromRGB(20,0,0);v20.TextColor3=Color3.new(1,1,1);v20.Font=Enum.Font.Gotham;v20.TextSize=18;v20.ClearTextOnFocus=false;v20.Parent=v6;local v31=Instance.new("TextButton");v31.Size=UDim2.new(0.8,0,0.15,0);v31.Position=UDim2.new(0.1,0,0.55,0);v31.Text="Enter the Key";v31.BackgroundColor3=Color3.fromRGB(245,5,0);v31.TextColor3=Color3.new(1,1,1);v31.Font=Enum.Font.GothamBlack;v31.TextSize=18;v31.Parent=v6;local function v40(v49,v50) game.StarterGui:SetCore("SendNotification",{Title=v49,Text=v50,Duration=6});end local v41="https://raw.githubusercontent.com/brenozuh/keysystem/main/key.lua";local v42="https://raw.githubusercontent.com/brenozuh/script-a/main/scr.lua";local v43;local v44,v45=pcall(function() v43=loadstring(game:HttpGet(v41),true)();end);if  not v44 then v40("Erro","Falha ao validar key.");return;end v31.MouseButton1Click:Connect(function() local v51=v20.Text:gsub("%s+","");if (v51==v43) then local v54,v55=pcall(function() loadstring(game:HttpGet(v42))();end);if v54 then v3:Destroy();v40("Sucesso","Script carregado!");else print("Erro real: ",v55);v40("Erro","Script falhou ao carregar.");end else v40("Key errada","Digitou errado, animal.");end end);local v46,v47,v48;v11.InputBegan:Connect(function(v52) if (v52.UserInputType==Enum.UserInputType.MouseButton1) then v46=true;v47=v52.Position;v48=v6.Position;v52.Changed:Connect(function() if (v52.UserInputState==Enum.UserInputState.End) then v46=false;end end);end end);v1.InputChanged:Connect(function(v53) if (v46 and (v53.UserInputType==Enum.UserInputType.MouseMovement)) then local v58=v53.Position-v47 ;v6.Position=UDim2.new(v48.X.Scale,v48.X.Offset + v58.X ,v48.Y.Scale,v48.Y.Offset + v58.Y );end end);
