--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--

if getgenv().scriptRodando then warn("Script já tá rodando, abortando...");return;end getgenv().scriptRodando=true;local v1=game:GetService("Players");local v2=game:GetService("UserInputService");local v3=v1.LocalPlayer;local v4=Instance.new("ScreenGui");v4.ResetOnSpawn=false;v4.Parent=v3:WaitForChild("PlayerGui");local v7=Instance.new("Frame");v7.Size=UDim2.new(0.3,0,0.4,0);v7.Position=UDim2.new(0.35,0,0.3,0);v7.BackgroundColor3=Color3.fromRGB(5,0,0);v7.Parent=v4;local v12=Instance.new("TextLabel");v12.Size=UDim2.new(1,0,0.2,0);v12.BackgroundColor3=Color3.fromRGB(255,10,0);v12.Text="gimme the key pls";v12.TextColor3=Color3.new(1,1,1);v12.Font=Enum.Font.GothamBlack;v12.TextSize=24;v12.Parent=v7;local v21=Instance.new("TextBox");v21.Size=UDim2.new(0.8,0,0.18,0);v21.Position=UDim2.new(0.1,0,0.32,0);v21.PlaceholderText="Type it";v21.BackgroundColor3=Color3.fromRGB(20,0,0);v21.TextColor3=Color3.new(1,1,1);v21.Font=Enum.Font.Gotham;v21.TextSize=18;v21.ClearTextOnFocus=false;v21.Parent=v7;local v32=Instance.new("TextButton");v32.Size=UDim2.new(0.8,0,0.15,0);v32.Position=UDim2.new(0.1,0,0.55,0);v32.Text="Enter the Key";v32.BackgroundColor3=Color3.fromRGB(245,5,0);v32.TextColor3=Color3.new(1,1,1);v32.Font=Enum.Font.GothamBlack;v32.TextSize=18;v32.Parent=v7;local function v41(v50,v51) game.StarterGui:SetCore("SendNotification",{Title=v50,Text=v51,Duration=6});end local v42="https://raw.githubusercontent.com/brenozuh/keysystem/main/key.lua";local v43="https://raw.githubusercontent.com/brenozuh/script-a/main/scr.lua";local v44;local v45,v46=pcall(function() v44=loadstring(game:HttpGet(v42),true)();end);if  not v45 then v41("Erro","Falha ao validar key.");return;end v32.MouseButton1Click:Connect(function() local v52=v21.Text:gsub("%s+","");if (v52==v44) then local v55,v56=pcall(function() loadstring(game:HttpGet(v43))();end);if v55 then v4:Destroy();v41("Sucesso","Script carregado!");else print("Erro real: ",v56);v41("Erro","Script falhou ao carregar.");end else v41("Key errada","Digitou errado, animal.");end end);local v47,v48,v49;v12.InputBegan:Connect(function(v53) if (v53.UserInputType==Enum.UserInputType.MouseButton1) then v47=true;v48=v53.Position;v49=v7.Position;v53.Changed:Connect(function() if (v53.UserInputState==Enum.UserInputState.End) then v47=false;end end);end end);v2.InputChanged:Connect(function(v54) if (v47 and (v54.UserInputType==Enum.UserInputType.MouseMovement)) then local v59=v54.Position-v48 ;v7.Position=UDim2.new(v49.X.Scale,v49.X.Offset + v59.X ,v49.Y.Scale,v49.Y.Offset + v59.Y );end end);
